apiVersion: batch/v1
kind: Job
metadata:
  name: initsqldatabasejob
  namespace: aks
  labels:
    version: 1.0.0
    product: init-sql-database-job
    environment: aks
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: sqljobcontainer
<<<<<<< HEAD
        image: logcorneracrms365.azurecr.io/todo-list-mssql-tools:latest
=======
        image: aksacrkhhdlog.azurecr.io/todo-list-mssql-tools:latest
>>>>>>> 39b422e99fbfad0ac6342eec3678187ee923c2f9
        imagePullPolicy: IfNotPresent
        command: ["/opt/mssql-tools/bin/sqlcmd"]
        args: [ "-S", "todo-list-db-service", "-d", "master", "-U", "sa", "-P", "MyC0m9l&xP@ssw0rd", "-I", "-i", "TodoList.Database_Create.sql" ]
      restartPolicy: Never
      imagePullSecrets:
        - name: registrysecret
 
